In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

In [3]:
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [6]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [4]:
from sklearn.model_selection import train_test_split

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [14]:
x_test

array([[    23,  48000],
       [    58,  23000],
       [    27,  31000],
       [    37,  57000],
       [    28,  89000],
       [    26, 118000],
       [    53,  34000],
       [    22,  81000],
       [    55, 130000],
       [    29,  83000],
       [    27,  20000],
       [    50,  20000],
       [    48,  33000],
       [    22,  63000],
       [    24,  32000],
       [    53,  82000],
       [    35,  97000],
       [    31,  89000],
       [    40,  78000],
       [    35,  79000],
       [    33,  60000],
       [    40, 142000],
       [    24,  55000],
       [    18,  68000],
       [    36,  63000],
       [    28,  84000],
       [    40,  71000],
       [    25,  79000],
       [    48, 119000],
       [    29,  80000],
       [    26,  86000],
       [    22,  55000],
       [    52, 150000],
       [    40,  61000],
       [    28,  87000],
       [    32,  18000],
       [    38,  50000],
       [    40, 107000],
       [    40,  59000],
       [    28,  44000],


In [8]:
from sklearn.preprocessing import StandardScaler

In [49]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [16]:
x_train

array([[ 0.44587723,  1.22785521],
       [-0.30665818, -1.34702997],
       [-0.30665818,  0.1327891 ],
       [-0.11852433,  0.19198186],
       [-0.30665818, -0.28156024],
       [ 0.16367645, -0.69590958],
       [-0.96512666, -0.45913853],
       [-1.24732744,  0.48794567],
       [-0.96512666, -0.340753  ],
       [-0.30665818, -0.60712044],
       [-0.68292588,  1.4054335 ],
       [-1.43546129,  0.33996377],
       [ 0.82214493, -0.57752406],
       [ 0.06960953,  1.52381902],
       [ 0.06960953,  0.01440357],
       [-0.30665818,  0.1327891 ],
       [ 1.19841263,  2.23413218],
       [ 0.82214493, -0.63671682],
       [ 0.06960953,  0.07359634],
       [-0.68292588, -0.07438557],
       [ 0.91621186,  0.57673482],
       [ 1.95094804,  0.16238548],
       [-0.0244574 , -0.45913853],
       [ 1.95094804,  0.51754206],
       [-0.21259125, -0.48873491],
       [ 0.82214493,  1.02068054],
       [ 0.91621186, -1.19904807],
       [-0.11852433,  0.04399995],
       [-1.81172899,

In [17]:
x_test

array([[-1.31711776, -0.55931676],
       [ 2.2731565 , -1.2789729 ],
       [-0.9068007 , -1.04868294],
       [ 0.11899195, -0.30024054],
       [-0.80422143,  0.62091932],
       [-1.00937996,  1.45572045],
       [ 1.76026018, -0.9623242 ],
       [-1.41969702,  0.39062936],
       [ 1.96541871,  1.8011554 ],
       [-0.70164217,  0.44820185],
       [-0.9068007 , -1.36533164],
       [ 1.45252239, -1.36533164],
       [ 1.24736386, -0.99111044],
       [-1.41969702, -0.12752307],
       [-1.21453849, -1.01989669],
       [ 1.76026018,  0.4194156 ],
       [-0.08616658,  0.85120929],
       [-0.49648364,  0.62091932],
       [ 0.42672974,  0.30427062],
       [-0.08616658,  0.33305686],
       [-0.29132511, -0.21388181],
       [ 0.42672974,  2.14659035],
       [-1.21453849, -0.35781304],
       [-1.83001408,  0.01640816],
       [ 0.01641268, -0.12752307],
       [-0.80422143,  0.47698809],
       [ 0.42672974,  0.1027669 ],
       [-1.11195923,  0.33305686],
       [ 1.24736386,

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
regressor = LogisticRegression()

In [20]:
regressor.fit(x_train, y_train)

LogisticRegression()

In [50]:
y_pred = regressor.predict(x_test)

In [51]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [27]:
regressor.predict(scaler.fit_transform([[30,87000]]))

array([0], dtype=int64)

In [53]:
y_test = y_test.reshape(len(y_test), 1)

In [55]:
y_pred = y_pred.reshape(len(y_pred), 1)

In [60]:
verdict = np.concatenate((y_test, y_pred), axis=1)

In [61]:
verdict

array([[0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1,

## Confusion Matrix

In [65]:
from sklearn.metrics import classification_report, confusion_matrix

In [64]:
print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.89      0.92      0.91        64
           1       0.85      0.81      0.83        36

    accuracy                           0.88       100
   macro avg       0.87      0.86      0.87       100
weighted avg       0.88      0.88      0.88       100



In [66]:
confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[59,  5],
       [ 7, 29]], dtype=int64)

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = scaler.inverse_transform(x_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, regressor.predict(scaler.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()a